# Generated by Django 4.1 on 2022-08-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("account_id", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(default="", max_length=100, unique=True)),
                ("nickname", models.CharField(default="", max_length=100, unique=True)),
                ("name", models.CharField(default="", max_length=100)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
